Feature/keywords from controlled vocabulary
Kungbib/fgs-oaipmh-ojs-plugin pull request #2
Opened 2021-05-10 13:27 UTC by lrosenstrom

Deliver linked keywords like this (following FGS-PUBL):
```
<mods:subject lang="swe" authority="sao" >
<mods:topic>Italienska som främmandespråk</mods:topic>
</mods:subject>
```
Also added support for delivering them like this, when mimer accepts the valueUri attribute:
```
<mods:subject lang="swe">
<mods:topic valueUri="https://id.kb.se/term/sao/Italienska%20som%20fr%C3%A4mmandespr%C3%A5k">Italienska som främmandespråk</mods:topic>
</mods:subject>
```
Anonymous keywords are delivered without the authority attribute:
```
<mods:subject lang="eng" >
<mods:topic>Fish</mods:topic>
</mods:subject> 
```

2021-05-10 15:14 UTC, olovy requested changes
Same comment as in https://github.com/Kungbib/idkbse-ojs-plugin/pull/1

I don't we should build on the assumption that prefLabel is part of the URI (even though it will work for SAO). Do we need to encode URI and label as one string to be stored in OJS?

We could merge this and do that as a separate update.

2021-05-10 15:21 UTC, olovy commented
i.e. we could do basically the same thing but store e.g. `<prefLabel>|<URI>`

2021-05-11 06:43 UTC, lrosenstrom commented
See discussion in https://github.com/Kungbib/idkbse-ojs-plugin/pull/1.

2021-05-11 14:16 UTC, olovy approved these changes
:ship:

2021-05-12 11:00 UTC, merged